-- First, remove the table if it exists
drop table if exists bookmarks;

-- Create the table anew
create table bookmarks (
  id INTEGER primary key generated by default as identity,
  title TEXT,
  url NVARCHAR(2083),
  description TEXT,
  rating NUMERIC
);

-- insert some test data
-- Using a multi-row insert statement here
insert into bookmarks (title, url, description, rating)
values
  ('Thinkful', 'https://www.thinkful.com', 'Think outside the classroom', 5),
  ('Google', 'https://www.google.com', 'Where we find everything else', 4),
  ('MDN', 'https://developer.mozilla.org', 'The only place to find web documentation', 5),
  ('Puppy Teeth Records', 'https://puppyteeth.org', 'The best cassette label', 10);

  -- id, title, url, description, rating 